version: '3'
services:
  server:
    container_name: server
    image: server:latest
    build:
      context: ./server
      args:
        - NODE_ENV=production
    volumes:
      - ./server:/app
      - /app/node_modules
    # environment:
    #   - PORT=3000
    #   - NODE_ENV=production
    env_file:
      - ./server/.env.prod
    command: npm run prod
