version: '3'
services:
  app:
    build:
      context: ./myApp
      args:
        - NODE_ENV=development
    volumes:
      - ./myApp:/app:ro
      - /app/node_modules
    # environment:
    #   - PORT=3000
    #   - NODE_ENV=development
    env_file:
      - ./myApp/.env.dev
    command: npm run dev
