version: '3'
services:
  server:
    container_name: server
    image: server:latest
    build:
      context: ./server
      args:
        - NODE_ENV=development
    volumes:
      - ./server:/app
      - /app/node_modules
    # environment:
    #   - PORT=3000
    #   - NODE_ENV=development
    env_file:
      - ./server/.env.dev
    command: npm run dev
