version: '3'
services:
  server:
    container_name: server
    image: server:latest
    build: ./server
    ports:
      - '3000:3000'
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - database

  database:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: taibui
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: tai_db
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: {}
